FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app ./
ENV PORT=80
EXPOSE 80
CMD ["sh", "-c", "npm run preview -- --host 0.0.0.0 --port ${PORT}"]
