-- Message replies, emoji reactions, per-user room leaving, and soft deletion.
-- Chat rows remain private behind the Edge Function's cookie-session checks.

alter table public.market_conversations
  add column if not exists buyer_left_at timestamptz,
  add column if not exists seller_left_at timestamptz;

alter table public.market_messages
  add column if not exists reply_to_message_id bigint references public.market_messages(id) on delete set null,
  add column if not exists deleted_at timestamptz;

create index if not exists market_messages_reply_idx
  on public.market_messages (reply_to_message_id)
  where reply_to_message_id is not null;

create table if not exists public.market_message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.market_messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  reaction text not null,
  created_at timestamptz not null default now(),
  constraint market_message_reactions_allowed check (reaction in ('HEART', 'CHECK', 'THUMBS_UP', 'SAD', 'COOL', 'LAUGH')),
  constraint market_message_reactions_one_per_kind unique (message_id, user_id, reaction)
);

create index if not exists market_message_reactions_message_idx
  on public.market_message_reactions (message_id, reaction);

alter table public.market_message_reactions enable row level security;
revoke all on public.market_message_reactions from public, anon, authenticated;
grant select, insert, delete on public.market_message_reactions to service_role;
grant delete on public.market_messages to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.get_market_chat_conversations(p_user_id bigint)
returns table (
  id bigint,
  item_id bigint,
  buyer_id bigint,
  seller_id bigint,
  created_at timestamptz,
  updated_at timestamptz,
  item_title text,
  peer_id bigint,
  peer_nickname text,
  peer_profile_image_path text,
  last_message_id bigint,
  last_message_body text,
  last_message_sender_id bigint,
  last_message_created_at timestamptz,
  unread_count bigint
)
language sql stable security definer set search_path = public
as $$
  select
    conversation.id, conversation.item_id, conversation.buyer_id, conversation.seller_id,
    conversation.created_at, conversation.updated_at, item.title, peer.id, peer.nickname,
    peer_blog.profile_image_path, last_message.id,
    case when last_message.deleted_at is null then last_message.body else '삭제된 메시지입니다.' end,
    last_message.sender_id, last_message.created_at, coalesce(unread.total, 0)
  from public.market_conversations conversation
  join public.market_items item on item.id = conversation.item_id
  join public.users peer on peer.id = case when conversation.buyer_id = p_user_id then conversation.seller_id else conversation.buyer_id end
  left join public.blogs peer_blog on peer_blog.owner_id = peer.id
  left join lateral (
    select message.id, message.body, message.sender_id, message.created_at, message.deleted_at
    from public.market_messages message
    where message.conversation_id = conversation.id
    order by message.id desc limit 1
  ) last_message on true
  left join lateral (
    select count(*)::bigint as total
    from public.market_messages message
    where message.conversation_id = conversation.id
      and message.sender_id <> p_user_id and message.read_at is null and message.deleted_at is null
  ) unread on true
  where (conversation.buyer_id = p_user_id and conversation.buyer_left_at is null)
     or (conversation.seller_id = p_user_id and conversation.seller_left_at is null)
  order by conversation.updated_at desc;
$$;

drop function if exists public.get_market_chat_messages(bigint, bigint, integer);
create function public.get_market_chat_messages(
  p_user_id bigint,
  p_conversation_id bigint,
  p_limit integer default 200
)
returns table (
  id bigint,
  conversation_id bigint,
  sender_id bigint,
  body text,
  read_at timestamptz,
  created_at timestamptz,
  deleted_at timestamptz,
  reply_to_message_id bigint,
  reply_body text,
  reply_sender_id bigint,
  reactions jsonb
)
language sql stable security definer set search_path = public
as $$
  select
    message.id, message.conversation_id, message.sender_id,
    case when message.deleted_at is null then message.body else '' end,
    message.read_at, message.created_at, message.deleted_at, message.reply_to_message_id,
    case when replied.deleted_at is null then replied.body when replied.id is not null then '삭제된 메시지입니다.' else null end,
    replied.sender_id,
    coalesce(reaction_summary.items, '[]'::jsonb)
  from public.market_messages message
  left join public.market_messages replied on replied.id = message.reply_to_message_id
  left join lateral (
    select jsonb_agg(jsonb_build_object(
      'type', grouped.reaction,
      'count', grouped.total,
      'reactedByMe', grouped.mine
    ) order by grouped.reaction) as items
    from (
      select reaction.reaction, count(*)::integer as total,
        bool_or(reaction.user_id = p_user_id) as mine
      from public.market_message_reactions reaction
      where reaction.message_id = message.id
      group by reaction.reaction
    ) grouped
  ) reaction_summary on true
  where message.conversation_id = p_conversation_id
    and exists (
      select 1 from public.market_conversations conversation
      where conversation.id = p_conversation_id
        and (conversation.buyer_id = p_user_id or conversation.seller_id = p_user_id)
    )
  order by message.id asc
  limit least(greatest(p_limit, 1), 200);
$$;

revoke all on function public.get_market_chat_conversations(bigint) from public, anon, authenticated;
revoke all on function public.get_market_chat_messages(bigint, bigint, integer) from public, anon, authenticated;
grant execute on function public.get_market_chat_conversations(bigint) to service_role;
grant execute on function public.get_market_chat_messages(bigint, bigint, integer) to service_role;

create or replace function public.notify_market_chat_change()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  target_conversation_id bigint;
begin
  if tg_table_name = 'market_message_reactions' then
    select conversation_id into target_conversation_id
    from public.market_messages where id = case when tg_op = 'DELETE' then old.message_id else new.message_id end;
  elsif tg_table_name = 'market_messages' then
    target_conversation_id := case when tg_op = 'DELETE' then old.conversation_id else new.conversation_id end;
  else
    target_conversation_id := case when tg_op = 'DELETE' then old.id else new.id end;
  end if;

  insert into public.market_chat_versions(id, version, updated_at)
  values (true, 1, clock_timestamp())
  on conflict (id) do update
    set version = public.market_chat_versions.version + 1, updated_at = excluded.updated_at;

  if to_regprocedure('realtime.send(jsonb,text,text,boolean)') is not null then
    execute 'select realtime.send($1, $2, $3, $4)'
      using jsonb_build_object('conversationId', target_conversation_id), 'changed', 'market-chat', false;
  end if;
  return null;
end;
$$;

drop trigger if exists market_messages_realtime_change on public.market_messages;
create trigger market_messages_realtime_change
after insert or update of read_at, deleted_at on public.market_messages
for each row execute function public.notify_market_chat_change();

drop trigger if exists market_message_reactions_realtime_change on public.market_message_reactions;
create trigger market_message_reactions_realtime_change
after insert or delete on public.market_message_reactions
for each row execute function public.notify_market_chat_change();
