create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null,
  password_hash text not null,
  nickname text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_email_normalized check (email = lower(trim(email))),
  constraint users_nickname_length check (char_length(nickname) between 2 and 30)
);

create unique index if not exists users_email_unique on public.users (email);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  session_hash text not null unique,
  user_id bigint references public.users(id) on delete cascade,
  csrf_token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sessions_user_id_idx on public.sessions (user_id);
create index if not exists sessions_expires_at_idx on public.sessions (expires_at);

alter table public.users enable row level security;
alter table public.sessions enable row level security;

comment on table public.users is 'API users. Passwords are stored only as bcrypt hashes.';
comment on table public.sessions is 'Server-side sessions and CSRF tokens used by the API.';
