-- Split the existing writer "classification" from the new blog category model,
-- then add post engagement and operator-managed home banners.

drop function if exists public.read_post(bigint, bigint);
drop view if exists public.post_details;

alter table public.blog_categories rename to blog_classifications;
alter table public.blog_classifications add column migrated_from_category boolean not null default false;
update public.blog_classifications set migrated_from_category = true;
alter index public.blog_categories_blog_idx rename to blog_classifications_blog_idx;
alter table public.blog_classifications rename constraint blog_categories_pkey to blog_classifications_pkey;
alter table public.blog_classifications rename constraint blog_categories_name_length to blog_classifications_name_length;
alter table public.blog_classifications rename constraint blog_categories_position_nonnegative to blog_classifications_position_nonnegative;
alter table public.blog_classifications rename constraint blog_categories_blog_id_normalized_name_key to blog_classifications_blog_id_normalized_name_key;
alter table public.blog_classifications rename constraint blog_categories_blog_id_position_key to blog_classifications_blog_id_position_key;
alter table public.posts rename column category_id to legacy_classification_id;

create table public.post_classifications (
  post_id bigint not null references public.posts(id) on delete cascade,
  classification_id bigint not null references public.blog_classifications(id) on delete restrict,
  position smallint not null,
  created_at timestamptz not null default now(),
  primary key (post_id, classification_id),
  unique (post_id, position),
  constraint post_classifications_position check (position between 0 and 4)
);

insert into public.post_classifications (post_id, classification_id, position)
select id, legacy_classification_id, 0
from public.posts
where legacy_classification_id is not null
on conflict do nothing;

alter table public.posts drop column legacy_classification_id;

create table public.blog_categories (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete restrict,
  name text not null,
  normalized_name text not null,
  position integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blog_categories_name_length check (char_length(name) between 1 and 30),
  constraint blog_categories_position_nonnegative check (position >= 0),
  unique (blog_id, normalized_name),
  unique (blog_id, position)
);

alter table public.posts add column category_id bigint references public.blog_categories(id) on delete restrict;

create index blog_categories_blog_idx_v2 on public.blog_categories (blog_id, position);
create index post_classifications_classification_idx on public.post_classifications (classification_id, post_id);

create table public.post_likes (
  user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table public.post_bookmarks (
  user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete restrict,
  parent_id bigint references public.post_comments(id) on delete restrict,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint post_comments_body_length check (char_length(body) between 1 and 1000)
);

create index post_likes_post_idx on public.post_likes (post_id);
create index post_bookmarks_post_idx on public.post_bookmarks (post_id);
create index post_comments_post_idx on public.post_comments (post_id, created_at, id);
create index post_comments_parent_idx on public.post_comments (parent_id) where parent_id is not null;

alter table public.users add column if not exists role text not null default 'USER';
alter table public.users add constraint users_role_check check (role in ('USER', 'ADMIN'));

create table public.home_banners (
  id bigint generated by default as identity primary key,
  eyebrow text not null default 'NOTICE · EVENT',
  title text not null,
  description text not null default '',
  image_url text,
  cta_label text not null default '자세히 보기',
  cta_url text not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  position smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_banners_title_length check (char_length(title) between 1 and 120),
  constraint home_banners_description_length check (char_length(description) <= 300),
  constraint home_banners_position check (position between 0 and 99),
  constraint home_banners_window check (ends_at is null or ends_at > starts_at)
);

create index home_banners_active_idx on public.home_banners (is_active, starts_at, ends_at, position);

alter table public.blog_classifications enable row level security;
alter table public.blog_categories enable row level security;
alter table public.post_classifications enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_bookmarks enable row level security;
alter table public.post_comments enable row level security;
alter table public.home_banners enable row level security;

revoke all on public.blog_classifications, public.blog_categories, public.post_classifications,
  public.post_likes, public.post_bookmarks, public.post_comments, public.home_banners
  from public, anon, authenticated;
grant select, insert, update, delete on public.blog_classifications, public.blog_categories,
  public.post_classifications, public.post_likes, public.post_bookmarks, public.post_comments,
  public.home_banners to service_role;
grant usage, select on all sequences in schema public to service_role;

create view public.post_details with (security_invoker = true) as
select p.id, p.blog_id, p.category_id, c.name as category_name, p.title, p.content,
  p.status, p.view_count, p.published_at, p.created_at, p.updated_at, p.deleted_at,
  p.purge_after, b.name as blog_name, b.slug as blog_slug, b.owner_id,
  u.nickname as author_nickname
from public.posts p
join public.blogs b on b.id = p.blog_id
join public.users u on u.id = b.owner_id
left join public.blog_categories c on c.id = p.category_id;

revoke all on public.post_details from public, anon, authenticated;
grant select on public.post_details to service_role;

create or replace function public.read_post(p_post_id bigint, p_request_user_id bigint default null)
returns setof public.post_details language plpgsql security definer set search_path = public as $$
declare target public.post_details%rowtype;
begin
  select * into target from public.post_details where id = p_post_id and deleted_at is null;
  if not found then return; end if;
  if target.status = 'DRAFT' and target.owner_id is distinct from p_request_user_id then return; end if;
  if target.status = 'PUBLISHED' then
    update public.posts set view_count = view_count + 1 where id = p_post_id;
    target.view_count := target.view_count + 1;
  end if;
  return next target;
end;
$$;

revoke all on function public.read_post(bigint, bigint) from public, anon, authenticated;
grant execute on function public.read_post(bigint, bigint) to service_role;
