create table public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id bigint not null references public.users(id) on delete cascade,
  actor_id bigint not null references public.users(id) on delete cascade,
  type text not null,
  post_id bigint not null references public.posts(id) on delete cascade,
  comment_id bigint references public.post_comments(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint notifications_type_check check (type in ('LIKE', 'REPLY')),
  constraint notifications_not_self check (recipient_id <> actor_id),
  constraint notifications_reply_comment check (
    (type = 'LIKE' and comment_id is null) or
    (type = 'REPLY' and comment_id is not null)
  )
);

create unique index notifications_like_once_idx
  on public.notifications (recipient_id, actor_id, post_id)
  where type = 'LIKE';

create unique index notifications_reply_once_idx
  on public.notifications (comment_id)
  where type = 'REPLY';

create index notifications_recipient_created_idx
  on public.notifications (recipient_id, created_at desc, id desc);

create index notifications_recipient_unread_idx
  on public.notifications (recipient_id, created_at desc)
  where read_at is null;

alter table public.notifications enable row level security;
revoke all on public.notifications from public, anon, authenticated;
grant select, insert, update, delete on public.notifications to service_role;

create or replace function public.notify_post_like()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient bigint;
begin
  select blog.owner_id into recipient
  from public.posts post
  join public.blogs blog on blog.id = post.blog_id
  where post.id = new.post_id;
  if recipient is not null and recipient <> new.user_id then
    insert into public.notifications (recipient_id, actor_id, type, post_id)
    values (recipient, new.user_id, 'LIKE', new.post_id)
    on conflict do nothing;
  end if;
  return new;
end;
$$;

create or replace function public.remove_post_like_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.notifications
  where type = 'LIKE' and actor_id = old.user_id and post_id = old.post_id;
  return old;
end;
$$;

create or replace function public.notify_comment_reply()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient bigint;
begin
  if new.parent_id is null then return new; end if;
  select author_id into recipient from public.post_comments where id = new.parent_id;
  if recipient is not null and recipient <> new.author_id then
    insert into public.notifications (recipient_id, actor_id, type, post_id, comment_id)
    values (recipient, new.author_id, 'REPLY', new.post_id, new.id)
    on conflict do nothing;
  end if;
  return new;
end;
$$;

create trigger notify_post_like_after_insert
after insert on public.post_likes
for each row execute function public.notify_post_like();

create trigger remove_post_like_notification_after_delete
after delete on public.post_likes
for each row execute function public.remove_post_like_notification();

create trigger notify_comment_reply_after_insert
after insert on public.post_comments
for each row execute function public.notify_comment_reply();

revoke all on function public.notify_post_like(), public.remove_post_like_notification(), public.notify_comment_reply() from public, anon, authenticated;
