alter table public.market_items
  add column if not exists image_urls text[] not null default '{}';

alter table public.market_items
  drop constraint if exists market_items_image_count;
alter table public.market_items
  add constraint market_items_image_count check (cardinality(image_urls) <= 5);

create table if not exists public.wallets (
  user_id bigint primary key references public.users(id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_orders (
  id bigint generated by default as identity primary key,
  item_id bigint not null unique references public.market_items(id) on delete restrict,
  buyer_id bigint not null references public.users(id) on delete restrict,
  seller_id bigint not null references public.users(id) on delete restrict,
  price_points bigint not null check (price_points > 0),
  status text not null default 'PAID' check (status in ('PAID', 'COMPLETED', 'CANCELLED')),
  paid_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_orders_participants check (buyer_id <> seller_id)
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  order_id bigint references public.market_orders(id) on delete restrict,
  type text not null check (type in ('INITIAL_GRANT', 'POINT_CHARGE', 'MARKET_PURCHASE', 'MARKET_SALE', 'REFUND')),
  amount bigint not null check (amount <> 0),
  balance_after bigint not null check (balance_after >= 0),
  created_at timestamptz not null default now()
);

create unique index if not exists wallet_initial_grant_unique
  on public.wallet_transactions (user_id) where type = 'INITIAL_GRANT';
create index if not exists market_orders_buyer_idx on public.market_orders (buyer_id, created_at desc);
create index if not exists market_orders_seller_idx on public.market_orders (seller_id, created_at desc);
create index if not exists wallet_transactions_user_idx on public.wallet_transactions (user_id, created_at desc);

insert into public.wallets (user_id, balance)
select id, 100000 from public.users
on conflict (user_id) do nothing;

insert into public.wallet_transactions (user_id, type, amount, balance_after)
select user_id, 'INITIAL_GRANT', 100000, balance
from public.wallets
where balance >= 100000
on conflict do nothing;

create or replace function public.initialize_user_wallet()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.wallets (user_id, balance) values (new.id, 100000)
  on conflict (user_id) do nothing;
  insert into public.wallet_transactions (user_id, type, amount, balance_after)
  values (new.id, 'INITIAL_GRANT', 100000, 100000)
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists users_initialize_wallet on public.users;
create trigger users_initialize_wallet
after insert on public.users
for each row execute function public.initialize_user_wallet();

create or replace function public.purchase_market_item(p_item_id bigint, p_buyer_id bigint)
returns table(order_id bigint, buyer_balance bigint, seller_balance bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.market_items%rowtype;
  v_order_id bigint;
  v_buyer_balance bigint;
  v_seller_balance bigint;
begin
  select * into v_item from public.market_items where id = p_item_id for update;
  if not found then raise exception 'ITEM_NOT_FOUND'; end if;
  if v_item.seller_id = p_buyer_id then raise exception 'SELF_PURCHASE_NOT_ALLOWED'; end if;
  if v_item.status <> 'SELLING' then raise exception 'ITEM_NOT_AVAILABLE'; end if;

  insert into public.wallets (user_id, balance) values (p_buyer_id, 0) on conflict do nothing;
  insert into public.wallets (user_id, balance) values (v_item.seller_id, 0) on conflict do nothing;
  select balance into v_buyer_balance from public.wallets where user_id = p_buyer_id for update;
  if v_buyer_balance < v_item.price_points then raise exception 'INSUFFICIENT_POINTS'; end if;

  update public.wallets set balance = balance - v_item.price_points, updated_at = now()
    where user_id = p_buyer_id returning balance into v_buyer_balance;
  update public.wallets set balance = balance + v_item.price_points, updated_at = now()
    where user_id = v_item.seller_id returning balance into v_seller_balance;
  insert into public.market_orders (item_id, buyer_id, seller_id, price_points)
    values (v_item.id, p_buyer_id, v_item.seller_id, v_item.price_points)
    returning id into v_order_id;
  update public.market_items set status = 'SOLD', updated_at = now() where id = v_item.id;
  insert into public.wallet_transactions (user_id, order_id, type, amount, balance_after) values
    (p_buyer_id, v_order_id, 'MARKET_PURCHASE', -v_item.price_points, v_buyer_balance),
    (v_item.seller_id, v_order_id, 'MARKET_SALE', v_item.price_points, v_seller_balance);
  return query select v_order_id, v_buyer_balance, v_seller_balance;
exception
  when unique_violation then raise exception 'ITEM_NOT_AVAILABLE';
end;
$$;

create or replace function public.complete_market_order(p_order_id bigint, p_buyer_id bigint)
returns public.market_orders
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.market_orders%rowtype;
begin
  select * into v_order from public.market_orders where id = p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if v_order.buyer_id <> p_buyer_id then raise exception 'ORDER_FORBIDDEN'; end if;
  if v_order.status <> 'PAID' then raise exception 'ORDER_NOT_COMPLETABLE'; end if;
  update public.market_orders set status = 'COMPLETED', completed_at = now(), updated_at = now()
    where id = p_order_id returning * into v_order;
  return v_order;
end;
$$;

create or replace function public.charge_wallet_points(p_user_id bigint, p_amount bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_balance bigint;
begin
  if p_amount not in (10000, 50000, 100000) then raise exception 'INVALID_CHARGE_AMOUNT'; end if;
  insert into public.wallets (user_id, balance) values (p_user_id, 0) on conflict do nothing;
  update public.wallets set balance = balance + p_amount, updated_at = now()
    where user_id = p_user_id returning balance into v_balance;
  insert into public.wallet_transactions (user_id, type, amount, balance_after)
    values (p_user_id, 'POINT_CHARGE', p_amount, v_balance);
  return v_balance;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('market-images', 'market-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

alter table public.wallets enable row level security;
alter table public.market_orders enable row level security;
alter table public.wallet_transactions enable row level security;
revoke all on public.wallets, public.market_orders, public.wallet_transactions from public, anon, authenticated;
grant select, insert, update on public.wallets, public.market_orders, public.wallet_transactions to service_role;
grant usage, select on all sequences in schema public to service_role;
revoke all on function public.purchase_market_item(bigint, bigint) from public, anon, authenticated;
revoke all on function public.complete_market_order(bigint, bigint) from public, anon, authenticated;
revoke all on function public.charge_wallet_points(bigint, bigint) from public, anon, authenticated;
grant execute on function public.purchase_market_item(bigint, bigint) to service_role;
grant execute on function public.complete_market_order(bigint, bigint) to service_role;
grant execute on function public.charge_wallet_points(bigint, bigint) to service_role;

comment on table public.wallets is 'MVP point balances. Points have no cash value.';
comment on table public.market_orders is 'Point-based market purchase records.';
