alter table public.users
  add column if not exists preference_onboarding_completed_at timestamptz;

create table if not exists public.interest_tags (
  id bigint generated by default as identity primary key,
  tag_key text not null unique,
  label text not null,
  group_key text not null,
  sort_order integer not null,
  constraint interest_tags_group check (group_key in ('WORK', 'FORM', 'APPEARANCE_RELATIONSHIP', 'PERSONALITY')),
  constraint interest_tags_sort_positive check (sort_order > 0),
  unique (group_key, sort_order)
);

insert into public.interest_tags (tag_key, label, group_key, sort_order) values
  ('work_vocaloid', '보컬로이드', 'WORK', 1),
  ('work_mascot', '마스코트', 'WORK', 2),
  ('work_virtual', '버추얼', 'WORK', 3),
  ('work_novel', '소설', 'WORK', 4),
  ('work_game', '게임', 'WORK', 5),
  ('work_anime_comics', '애니메이션/만화', 'WORK', 6),
  ('work_2_5d_3d', '2.5차원/3D', 'WORK', 7),
  ('work_category', '작품 카테고리', 'WORK', 8),
  ('work_idol_character', '아이돌 캐릭터', 'WORK', 9),
  ('work_original_character', '자작 캐릭터', 'WORK', 10),
  ('form_original', '원작', 'FORM', 1),
  ('form_official', '공식', 'FORM', 2),
  ('form_collection', '수집', 'FORM', 3),
  ('form_game', '게임', 'FORM', 4),
  ('form_primary_creation', '1차 창작', 'FORM', 5),
  ('form_secondary_creation', '2차 창작', 'FORM', 6),
  ('relation_cat_face', '고양이상', 'APPEARANCE_RELATIONSHIP', 1),
  ('relation_dumb_dumber', '덤앤더머', 'APPEARANCE_RELATIONSHIP', 2),
  ('relation_slicked_hair', '깐머', 'APPEARANCE_RELATIONSHIP', 3),
  ('relation_beastfolk', '수인', 'APPEARANCE_RELATIONSHIP', 4),
  ('relation_mastermind', '흑막', 'APPEARANCE_RELATIONSHIP', 5),
  ('relation_dog_face', '강아지상', 'APPEARANCE_RELATIONSHIP', 6),
  ('relation_odd_eyes', '오드아이', 'APPEARANCE_RELATIONSHIP', 7),
  ('relation_blond_white_hair', '금발/백발', 'APPEARANCE_RELATIONSHIP', 8),
  ('relation_trust_bond', '신뢰&유대', 'APPEARANCE_RELATIONSHIP', 9),
  ('relation_salvation', '구원 서사', 'APPEARANCE_RELATIONSHIP', 10),
  ('relation_teacher_student', '스승&제자', 'APPEARANCE_RELATIONSHIP', 11),
  ('relation_master_servant', '주종', 'APPEARANCE_RELATIONSHIP', 12),
  ('relation_long_haired_man', '장발남', 'APPEARANCE_RELATIONSHIP', 13),
  ('relation_pure_love', '순애', 'APPEARANCE_RELATIONSHIP', 14),
  ('relation_love_triangle', '삼각관계', 'APPEARANCE_RELATIONSHIP', 15),
  ('relation_contract', '계약 관계', 'APPEARANCE_RELATIONSHIP', 16),
  ('relation_snake_face', '뱀상', 'APPEARANCE_RELATIONSHIP', 17),
  ('relation_black_hair', '흑발', 'APPEARANCE_RELATIONSHIP', 18),
  ('relation_hate', '혐관', 'APPEARANCE_RELATIONSHIP', 19),
  ('relation_unrequited_love', '짝사랑', 'APPEARANCE_RELATIONSHIP', 20),
  ('relation_narrative_driven', '서사 중심', 'APPEARANCE_RELATIONSHIP', 21),
  ('relation_duo', '콤비', 'APPEARANCE_RELATIONSHIP', 22),
  ('relation_rivals', '앙숙', 'APPEARANCE_RELATIONSHIP', 23),
  ('relation_bangs', '덮머', 'APPEARANCE_RELATIONSHIP', 24),
  ('personality_sunshine', '햇살캐', 'PERSONALITY', 1),
  ('personality_mature', '어른스러운', 'PERSONALITY', 2),
  ('personality_cautious', '신중한', 'PERSONALITY', 3),
  ('personality_pure', '순수한', 'PERSONALITY', 4),
  ('personality_eccentric', '별난', 'PERSONALITY', 5),
  ('personality_kind', '다정한', 'PERSONALITY', 6),
  ('personality_optimistic', '낙천적', 'PERSONALITY', 7),
  ('personality_introverted', '내성적', 'PERSONALITY', 8),
  ('personality_violent', '폭력적인', 'PERSONALITY', 9),
  ('personality_obsessive', '집착적', 'PERSONALITY', 10),
  ('personality_affection_deprived', '애정결핍인', 'PERSONALITY', 11),
  ('personality_hypocritical', '위선적', 'PERSONALITY', 12),
  ('personality_timid', '소심한', 'PERSONALITY', 13),
  ('personality_unstable', '불안정한', 'PERSONALITY', 14),
  ('personality_cynical', '냉소적', 'PERSONALITY', 15),
  ('personality_cold', '냉담한', 'PERSONALITY', 16),
  ('personality_cheerful', '쾌활한', 'PERSONALITY', 17),
  ('personality_puppy', '댕댕이', 'PERSONALITY', 18),
  ('personality_decadent', '퇴폐미', 'PERSONALITY', 19),
  ('personality_sly', '능글맞은', 'PERSONALITY', 20),
  ('personality_menhera', '멘헤라', 'PERSONALITY', 21),
  ('personality_yandere', '얀데레', 'PERSONALITY', 22),
  ('personality_tsundere', '츤데레', 'PERSONALITY', 23),
  ('personality_righteous', '정의로운', 'PERSONALITY', 24)
on conflict (tag_key) do update set
  label = excluded.label,
  group_key = excluded.group_key,
  sort_order = excluded.sort_order;

create table if not exists public.user_preferences (
  user_id bigint not null references public.users(id) on delete cascade,
  tag_id bigint not null references public.interest_tags(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (user_id, tag_id)
);

create table if not exists public.post_interest_tags (
  post_id bigint not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.interest_tags(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (post_id, tag_id)
);

create index if not exists user_preferences_tag_id_idx on public.user_preferences (tag_id);
create index if not exists post_interest_tags_tag_id_idx on public.post_interest_tags (tag_id);
alter table public.interest_tags enable row level security;
alter table public.user_preferences enable row level security;
alter table public.post_interest_tags enable row level security;

create or replace function public.replace_user_preferences(p_user_id bigint, p_tag_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if cardinality(p_tag_ids) <> (select count(distinct value) from unnest(p_tag_ids) value) then
    raise exception 'DUPLICATE_TAGS';
  end if;
  if (select count(*) from interest_tags where id = any(p_tag_ids)) <> cardinality(p_tag_ids) then
    raise exception 'INVALID_TAG';
  end if;
  if exists (
    select 1 from interest_tags where id = any(p_tag_ids)
    group by group_key having count(*) > 3
  ) then
    raise exception 'GROUP_LIMIT_EXCEEDED';
  end if;

  delete from user_preferences where user_id = p_user_id;
  insert into user_preferences (user_id, tag_id)
    select p_user_id, value from unnest(p_tag_ids) value;
  update users set preference_onboarding_completed_at = coalesce(preference_onboarding_completed_at, now()), updated_at = now()
    where id = p_user_id;
end;
$$;

create or replace function public.replace_post_interest_tags(p_post_id bigint, p_tag_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if cardinality(p_tag_ids) > 10 then raise exception 'TAG_LIMIT_EXCEEDED'; end if;
  if cardinality(p_tag_ids) <> (select count(distinct value) from unnest(p_tag_ids) value) then
    raise exception 'DUPLICATE_TAGS';
  end if;
  if (select count(*) from interest_tags where id = any(p_tag_ids)) <> cardinality(p_tag_ids) then
    raise exception 'INVALID_TAG';
  end if;

  delete from post_interest_tags where post_id = p_post_id;
  insert into post_interest_tags (post_id, tag_id)
    select p_post_id, value from unnest(p_tag_ids) value;
end;
$$;

revoke all on function public.replace_user_preferences(bigint, bigint[]) from public, anon, authenticated;
revoke all on function public.replace_post_interest_tags(bigint, bigint[]) from public, anon, authenticated;
grant execute on function public.replace_user_preferences(bigint, bigint[]) to service_role;
grant execute on function public.replace_post_interest_tags(bigint, bigint[]) to service_role;
grant select, insert, update, delete on table public.interest_tags to service_role;
grant select, insert, update, delete on table public.user_preferences to service_role;
grant select, insert, update, delete on table public.post_interest_tags to service_role;
