create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  owner_id bigint not null unique references public.users(id) on delete restrict,
  name text not null,
  slug text not null unique,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blogs_name_length check (char_length(name) between 2 and 30),
  constraint blogs_slug_format check (slug ~ '^[a-z0-9-]{3,30}$'),
  constraint blogs_description_length check (char_length(description) <= 160)
);

create index if not exists blogs_owner_id_idx on public.blogs (owner_id);
alter table public.blogs enable row level security;
