alter table public.blogs add column if not exists profile_image_path text;

create table if not exists public.blog_categories (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete restrict,
  name text not null,
  normalized_name text not null,
  position integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blog_categories_name_length check (char_length(name) between 1 and 30),
  constraint blog_categories_position_nonnegative check (position >= 0),
  unique (blog_id, normalized_name),
  unique (blog_id, position)
);

create index if not exists blog_categories_blog_idx on public.blog_categories (blog_id, position);
alter table public.blog_categories enable row level security;
revoke all on public.blog_categories from public, anon, authenticated;
grant select, insert, update, delete on public.blog_categories to service_role;
grant usage, select on all sequences in schema public to service_role;

alter table public.posts add column if not exists category_id bigint references public.blog_categories(id) on delete restrict;
alter table public.posts add column if not exists deleted_at timestamptz;
alter table public.posts add column if not exists purge_after timestamptz;
alter table public.market_items add column if not exists deleted_at timestamptz;
alter table public.market_items add column if not exists purge_after timestamptz;

create index if not exists posts_trash_idx on public.posts (blog_id, deleted_at desc) where deleted_at is not null;
create index if not exists market_items_trash_idx on public.market_items (seller_id, deleted_at desc) where deleted_at is not null;

drop function if exists public.read_post(bigint, bigint);
drop view if exists public.post_details;

create view public.post_details
with (security_invoker = true)
as
select
  p.id,
  p.blog_id,
  p.category_id,
  c.name as category_name,
  p.title,
  p.content,
  p.status,
  p.view_count,
  p.published_at,
  p.created_at,
  p.updated_at,
  p.deleted_at,
  p.purge_after,
  b.name as blog_name,
  b.slug as blog_slug,
  b.owner_id,
  u.nickname as author_nickname
from public.posts p
join public.blogs b on b.id = p.blog_id
join public.users u on u.id = b.owner_id
left join public.blog_categories c on c.id = p.category_id;

revoke all on public.post_details from public, anon, authenticated;
grant select on public.post_details to service_role;

create or replace function public.read_post(p_post_id bigint, p_request_user_id bigint default null)
returns setof public.post_details
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.post_details%rowtype;
begin
  select * into target from public.post_details where id = p_post_id and deleted_at is null;
  if not found then return; end if;
  if target.status = 'DRAFT' and target.owner_id is distinct from p_request_user_id then return; end if;
  if target.status = 'PUBLISHED' then
    update public.posts set view_count = view_count + 1 where id = p_post_id;
    target.view_count := target.view_count + 1;
  end if;
  return next target;
end;
$$;

revoke all on function public.read_post(bigint, bigint) from public, anon, authenticated;
grant execute on function public.read_post(bigint, bigint) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('blog-profile-images', 'blog-profile-images', true, 2097152, array['image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.purge_blog_trash()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.posts where purge_after is not null and purge_after <= now();

  delete from public.market_items mi
  where mi.purge_after is not null and mi.purge_after <= now()
    and not exists (select 1 from public.market_conversations mc where mc.item_id = mi.id);

  update public.market_items mi set
    title = '[삭제된 상품]', description = '삭제된 상품입니다.', category = '삭제됨', tags = '{}',
    purge_after = null, updated_at = now()
  where mi.purge_after is not null and mi.purge_after <= now()
    and exists (select 1 from public.market_conversations mc where mc.item_id = mi.id);
end;
$$;

revoke all on function public.purge_blog_trash() from public, anon, authenticated;
grant execute on function public.purge_blog_trash() to service_role;

do $$
begin
  if to_regclass('cron.job') is not null then
    execute $cron$select cron.schedule('purge-blog-trash-daily', '17 3 * * *', 'select public.purge_blog_trash()')
      where not exists (select 1 from cron.job where jobname = 'purge-blog-trash-daily')$cron$;
  end if;
end $$;
