-- Administrator console identity, account lifecycle and auditable wallet operations.

alter table public.users add column if not exists login_id text;
alter table public.users add column if not exists account_status text not null default 'ACTIVE';
alter table public.users add column if not exists withdrawn_at timestamptz;
alter table public.users add column if not exists password_change_required boolean not null default false;

create unique index if not exists users_login_id_unique
  on public.users (login_id) where login_id is not null;

alter table public.users drop constraint if exists users_account_status_check;
alter table public.users add constraint users_account_status_check
  check (account_status in ('ACTIVE', 'BLOCKED', 'WITHDRAWN'));

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id bigint not null references public.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text not null,
  reason text,
  before_value jsonb,
  after_value jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_latest_idx
  on public.admin_audit_logs (created_at desc, id desc);

alter table public.admin_audit_logs enable row level security;
revoke all on public.admin_audit_logs from public, anon, authenticated;
grant select, insert on public.admin_audit_logs to service_role;

alter table public.wallet_transactions add column if not exists reason text;
alter table public.wallet_transactions add column if not exists admin_actor_id bigint references public.users(id) on delete restrict;
alter table public.wallet_transactions drop constraint if exists wallet_transactions_type_check;
alter table public.wallet_transactions add constraint wallet_transactions_type_check
  check (type in ('INITIAL_GRANT', 'POINT_CHARGE', 'MARKET_PURCHASE', 'MARKET_SALE', 'REFUND', 'MISSION_REWARD', 'ADMIN_ADJUSTMENT'));

create or replace function public.set_admin_wallet_balance(
  p_admin_id bigint,
  p_user_id bigint,
  p_target_balance bigint,
  p_reason text
)
returns table(balance bigint, adjustment bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current bigint;
  v_delta bigint;
begin
  if p_target_balance < 0 or p_reason is null or char_length(trim(p_reason)) < 2 then
    raise exception 'INVALID_WALLET_ADJUSTMENT';
  end if;
  if not exists (select 1 from public.users where id = p_admin_id and role = 'ADMIN' and account_status = 'ACTIVE') then
    raise exception 'ADMIN_REQUIRED';
  end if;
  insert into public.wallets(user_id, balance) values (p_user_id, 0) on conflict do nothing;
  select wallets.balance into v_current from public.wallets where user_id = p_user_id for update;
  v_delta := p_target_balance - v_current;
  update public.wallets set balance = p_target_balance, updated_at = now() where user_id = p_user_id;
  if v_delta <> 0 then
    insert into public.wallet_transactions(user_id, type, amount, balance_after, reason, admin_actor_id)
    values (p_user_id, 'ADMIN_ADJUSTMENT', v_delta, p_target_balance, trim(p_reason), p_admin_id);
  end if;
  return query select p_target_balance, v_delta;
end;
$$;

revoke all on function public.set_admin_wallet_balance(bigint, bigint, bigint, text) from public, anon, authenticated;
grant execute on function public.set_admin_wallet_balance(bigint, bigint, bigint, text) to service_role;

insert into public.users(email, password_hash, nickname, role, login_id, account_status)
values (
  'admin@internal.invalid',
  '$2b$12$ux09z0ypMBjVamlP9AIRTeDbD6jwX8oSs52Ea4VtVghyFoyPfgBK.',
  '관리자',
  'ADMIN',
  'admin',
  'ACTIVE'
)
on conflict (email) do update set
  password_hash = excluded.password_hash, role = 'ADMIN', login_id = 'admin', account_status = 'ACTIVE';

insert into public.blogs(owner_id, name, slug, description)
select id, '공지사항', 'admin', '서비스 운영 공지와 주요 안내를 전합니다.'
from public.users where login_id = 'admin'
on conflict (owner_id) do update set name = excluded.name, slug = excluded.slug, description = excluded.description;

comment on table public.admin_audit_logs is 'Append-only audit trail for administrator mutations.';
