create table public.ai_missions (
  id text primary key,
  title text not null,
  description text not null,
  route text not null,
  event_type text not null check (event_type in ('POST_SAVED', 'MARKET_DETAIL_VIEWED')),
  reward_points bigint not null check (reward_points > 0),
  position integer not null check (position > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.ai_missions (id, title, description, route, event_type, reward_points, position) values
  ('draft-story', '첫 기록 남기기', '제목과 30자 이상의 본문을 작성하고 임시 저장하세요.', '/write', 'POST_SAVED', 100, 1),
  ('interest-classification', '관심분야 연결하기', '관심분야 기반 분류를 하나 이상 선택해 글에 적용하세요.', '/write', 'POST_SAVED', 150, 2),
  ('market-visit', '취향 상품 발견하기', '마켓 목록을 둘러보고 상품 상세 페이지 한 곳을 방문하세요.', '/market', 'MARKET_DETAIL_VIEWED', 80, 3)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  route = excluded.route,
  event_type = excluded.event_type,
  reward_points = excluded.reward_points,
  position = excluded.position,
  active = true,
  updated_at = now();

create table public.ai_companion_profiles (
  user_id bigint primary key references public.users(id) on delete cascade,
  character_id text check (character_id in ('chiikawa', 'hachiware', 'usagi')),
  memory_summary text not null default '' check (char_length(memory_summary) <= 1000),
  consented_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_conversations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  character_id text not null check (character_id in ('chiikawa', 'hachiware', 'usagi')),
  mode text not null check (mode in ('GENERAL', 'MISSION')),
  mission_id text references public.ai_missions(id) on delete restrict,
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'PAUSED', 'COMPLETED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_conversations_mission_mode check ((mode = 'MISSION') = (mission_id is not null))
);

create unique index ai_conversations_one_active on public.ai_conversations(user_id) where status = 'ACTIVE';
create index ai_conversations_user_recent on public.ai_conversations(user_id, updated_at desc);

create table public.ai_mission_progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  mission_id text not null references public.ai_missions(id) on delete restrict,
  conversation_id bigint references public.ai_conversations(id) on delete set null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'PAUSED', 'COMPLETED')),
  reward_points bigint not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, mission_id)
);

create unique index ai_mission_progress_one_active on public.ai_mission_progress(user_id) where status = 'ACTIVE';

create table public.ai_daily_user_usage (
  user_id bigint not null references public.users(id) on delete cascade,
  usage_date date not null,
  turn_count integer not null default 0 check (turn_count between 0 and 20),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create table public.ai_daily_global_usage (
  usage_date date primary key,
  turn_count integer not null default 0 check (turn_count between 0 and 200),
  updated_at timestamptz not null default now()
);

create table public.ai_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id bigint not null references public.ai_conversations(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null check (role in ('USER', 'ASSISTANT', 'SYSTEM')),
  body text not null check (char_length(body) between 1 and 2000),
  status text not null check (status in ('PENDING', 'COMPLETED', 'FALLBACK', 'FAILED')),
  idempotency_key text,
  usage_date date,
  emotion text,
  model text,
  input_tokens integer,
  output_tokens integer,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create unique index ai_messages_idempotency on public.ai_messages(user_id, idempotency_key) where idempotency_key is not null;
create index ai_messages_conversation_recent on public.ai_messages(conversation_id, created_at desc);
create index ai_messages_pending on public.ai_messages(created_at) where status = 'PENDING';

alter table public.wallet_transactions add column if not exists mission_progress_id bigint references public.ai_mission_progress(id) on delete restrict;
alter table public.wallet_transactions drop constraint if exists wallet_transactions_type_check;
alter table public.wallet_transactions add constraint wallet_transactions_type_check
  check (type in ('INITIAL_GRANT', 'POINT_CHARGE', 'MARKET_PURCHASE', 'MARKET_SALE', 'REFUND', 'MISSION_REWARD'));
create unique index wallet_mission_reward_unique on public.wallet_transactions(mission_progress_id) where mission_progress_id is not null;

create or replace function public.ai_kst_date()
returns date language sql stable as $$
  select (current_timestamp at time zone 'Asia/Seoul')::date
$$;

create or replace function public.ai_reconcile_stale_turns()
returns void language plpgsql security definer set search_path = public as $$
declare stale record;
begin
  for stale in
    with released as (
      update ai_messages
      set status = 'FAILED', completed_at = now()
      where status = 'PENDING' and created_at < now() - interval '5 minutes'
      returning user_id, usage_date
    )
    select user_id, usage_date, count(*)::integer as count
    from released where usage_date is not null group by user_id, usage_date
  loop
    update ai_daily_global_usage set turn_count = greatest(0, turn_count - stale.count), updated_at = now()
      where usage_date = stale.usage_date;
    update ai_daily_user_usage set turn_count = greatest(0, turn_count - stale.count), updated_at = now()
      where user_id = stale.user_id and usage_date = stale.usage_date;
  end loop;
end;
$$;

create or replace function public.reserve_ai_turn(
  p_user_id bigint,
  p_conversation_id bigint,
  p_body text,
  p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_day date := ai_kst_date();
  v_user_count integer;
  v_global_count integer;
  v_message_id uuid;
  v_existing ai_messages%rowtype;
begin
  perform ai_reconcile_stale_turns();
  select * into v_existing from ai_messages where user_id = p_user_id and idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('status', 'DUPLICATE', 'messageId', v_existing.id, 'messageStatus', v_existing.status);
  end if;
  if char_length(trim(p_body)) < 1 or char_length(trim(p_body)) > 300 then
    return jsonb_build_object('status', 'INVALID');
  end if;
  if not exists (select 1 from ai_conversations where id = p_conversation_id and user_id = p_user_id and status = 'ACTIVE') then
    return jsonb_build_object('status', 'CONVERSATION_NOT_FOUND');
  end if;
  if (select count(*) from ai_messages where user_id = p_user_id and role = 'USER' and status in ('PENDING', 'COMPLETED') and created_at > now() - interval '1 minute') >= 5 then
    return jsonb_build_object('status', 'RATE_LIMITED');
  end if;

  insert into ai_daily_global_usage (usage_date) values (v_day) on conflict do nothing;
  select turn_count into v_global_count from ai_daily_global_usage where usage_date = v_day for update;
  if v_global_count >= 200 then return jsonb_build_object('status', 'GLOBAL_LIMITED'); end if;

  insert into ai_daily_user_usage (user_id, usage_date) values (p_user_id, v_day) on conflict do nothing;
  select turn_count into v_user_count from ai_daily_user_usage where user_id = p_user_id and usage_date = v_day for update;
  if v_user_count >= 20 then return jsonb_build_object('status', 'USER_LIMITED'); end if;

  update ai_daily_global_usage set turn_count = turn_count + 1, updated_at = now() where usage_date = v_day;
  update ai_daily_user_usage set turn_count = turn_count + 1, updated_at = now() where user_id = p_user_id and usage_date = v_day;
  insert into ai_messages (conversation_id, user_id, role, body, status, idempotency_key, usage_date)
    values (p_conversation_id, p_user_id, 'USER', trim(p_body), 'PENDING', p_idempotency_key, v_day)
    returning id into v_message_id;
  return jsonb_build_object('status', 'RESERVED', 'messageId', v_message_id, 'userRemainingTurns', 19 - v_user_count, 'globalRemainingTurns', 199 - v_global_count);
exception when unique_violation then
  select * into v_existing from ai_messages where user_id = p_user_id and idempotency_key = p_idempotency_key;
  return jsonb_build_object('status', 'DUPLICATE', 'messageId', v_existing.id, 'messageStatus', v_existing.status);
end;
$$;

create or replace function public.finish_ai_turn(
  p_user_id bigint,
  p_message_id uuid,
  p_reply text,
  p_emotion text,
  p_memory_summary text,
  p_model text,
  p_input_tokens integer,
  p_output_tokens integer,
  p_fallback boolean default false
) returns boolean language plpgsql security definer set search_path = public as $$
declare v_message ai_messages%rowtype;
begin
  select * into v_message from ai_messages where id = p_message_id and user_id = p_user_id for update;
  if not found or v_message.status <> 'PENDING' then return false; end if;
  update ai_messages set status = case when p_fallback then 'FALLBACK' else 'COMPLETED' end, completed_at = now() where id = p_message_id;
  if p_fallback then
    update ai_daily_global_usage set turn_count = greatest(0, turn_count - 1), updated_at = now() where usage_date = v_message.usage_date;
    update ai_daily_user_usage set turn_count = greatest(0, turn_count - 1), updated_at = now() where user_id = p_user_id and usage_date = v_message.usage_date;
  else
    update ai_companion_profiles set memory_summary = left(coalesce(p_memory_summary, ''), 1000), updated_at = now() where user_id = p_user_id;
  end if;
  insert into ai_messages (conversation_id, user_id, role, body, status, emotion, model, input_tokens, output_tokens, completed_at)
    values (v_message.conversation_id, p_user_id, 'ASSISTANT', left(p_reply, 2000), case when p_fallback then 'FALLBACK' else 'COMPLETED' end,
      left(coalesce(p_emotion, ''), 40), p_model, p_input_tokens, p_output_tokens, now());
  return true;
end;
$$;

create or replace function public.complete_ai_mission(p_user_id bigint, p_event_type text, p_evidence jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_progress ai_mission_progress%rowtype; v_mission ai_missions%rowtype; v_balance bigint; v_valid boolean := false; v_character text; v_general_id bigint;
begin
  select * into v_progress from ai_mission_progress where user_id = p_user_id and status = 'ACTIVE' for update;
  if not found then return jsonb_build_object('completed', false); end if;
  select * into v_mission from ai_missions where id = v_progress.mission_id and active = true;
  if not found or v_mission.event_type <> p_event_type then return jsonb_build_object('completed', false); end if;
  if v_mission.id = 'draft-story' then
    v_valid := p_evidence->>'status' = 'DRAFT' and coalesce((p_evidence->>'titleLength')::integer, 0) > 0 and coalesce((p_evidence->>'contentLength')::integer, 0) >= 30;
  elsif v_mission.id = 'interest-classification' then
    v_valid := coalesce((p_evidence->>'interestClassificationCount')::integer, 0) > 0;
  elsif v_mission.id = 'market-visit' then
    v_valid := p_event_type = 'MARKET_DETAIL_VIEWED';
  end if;
  if not v_valid then return jsonb_build_object('completed', false); end if;

  select character_id into v_character from ai_conversations where id = v_progress.conversation_id;
  update ai_mission_progress set status = 'COMPLETED', completed_at = now(), updated_at = now() where id = v_progress.id;
  update ai_conversations set status = 'COMPLETED', updated_at = now() where id = v_progress.conversation_id;
  insert into ai_conversations (user_id, character_id, mode) values (p_user_id, v_character, 'GENERAL') returning id into v_general_id;
  insert into ai_messages (conversation_id, user_id, role, body, status, completed_at)
    values (v_general_id, p_user_id, 'SYSTEM', '미션 완료가 확인됐어요. 일반 대화로 돌아왔습니다.', 'COMPLETED', now());
  insert into wallets (user_id, balance) values (p_user_id, 0) on conflict do nothing;
  update wallets set balance = balance + v_progress.reward_points, updated_at = now() where user_id = p_user_id returning balance into v_balance;
  insert into wallet_transactions (user_id, mission_progress_id, type, amount, balance_after)
    values (p_user_id, v_progress.id, 'MISSION_REWARD', v_progress.reward_points, v_balance)
    on conflict (mission_progress_id) where mission_progress_id is not null do nothing;
  return jsonb_build_object('completed', true, 'missionId', v_progress.mission_id, 'rewardPoints', v_progress.reward_points, 'balance', v_balance);
end;
$$;

alter table public.ai_missions enable row level security;
alter table public.ai_companion_profiles enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_mission_progress enable row level security;
alter table public.ai_messages enable row level security;
alter table public.ai_daily_user_usage enable row level security;
alter table public.ai_daily_global_usage enable row level security;

revoke all on public.ai_missions, public.ai_companion_profiles, public.ai_conversations, public.ai_mission_progress, public.ai_messages, public.ai_daily_user_usage, public.ai_daily_global_usage from public, anon, authenticated;
grant select, insert, update, delete on public.ai_missions, public.ai_companion_profiles, public.ai_conversations, public.ai_mission_progress, public.ai_messages, public.ai_daily_user_usage, public.ai_daily_global_usage to service_role;
grant usage, select on all sequences in schema public to service_role;
revoke all on function public.reserve_ai_turn(bigint, bigint, text, text), public.finish_ai_turn(bigint, uuid, text, text, text, text, integer, integer, boolean), public.complete_ai_mission(bigint, text, jsonb), public.ai_reconcile_stale_turns() from public, anon, authenticated;
grant execute on function public.reserve_ai_turn(bigint, bigint, text, text), public.finish_ai_turn(bigint, uuid, text, text, text, text, integer, integer, boolean), public.complete_ai_mission(bigint, text, jsonb), public.ai_reconcile_stale_turns() to service_role;
