create table public.market_item_images (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.market_items(id) on delete cascade,
  storage_path text not null unique,
  position smallint not null,
  created_at timestamptz not null default now(),
  constraint market_item_images_position check (position between 0 and 4),
  constraint market_item_images_item_position unique (item_id, position)
);

create index market_item_images_item_idx on public.market_item_images (item_id, position);

alter table public.market_item_images enable row level security;
revoke all on public.market_item_images from public, anon, authenticated;
grant select, insert, update, delete on public.market_item_images to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('market-item-images', 'market-item-images', true, 2097152, array['image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.replace_market_item_images(p_item_id bigint, p_paths text[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if cardinality(p_paths) < 1 or cardinality(p_paths) > 5 then
    raise exception 'market item images must contain between 1 and 5 paths';
  end if;
  if exists (select 1 from unnest(p_paths) path group by path having count(*) > 1) then
    raise exception 'market item image paths must be unique';
  end if;
  delete from public.market_item_images where item_id = p_item_id;
  insert into public.market_item_images (item_id, storage_path, position)
  select p_item_id, path, (ordinality - 1)::smallint
  from unnest(p_paths) with ordinality as image(path, ordinality);
end;
$$;

revoke all on function public.replace_market_item_images(bigint, text[]) from public, anon, authenticated;
grant execute on function public.replace_market_item_images(bigint, text[]) to service_role;
