create table if not exists public.market_conversations (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.market_items(id) on delete restrict,
  buyer_id bigint not null references public.users(id) on delete restrict,
  seller_id bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_conversations_participants check (buyer_id <> seller_id),
  constraint market_conversations_unique_buyer unique (item_id, buyer_id)
);

create table if not exists public.market_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.market_conversations(id) on delete cascade,
  sender_id bigint not null references public.users(id) on delete restrict,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint market_messages_body_length check (char_length(body) between 1 and 1000)
);

create index if not exists market_conversations_buyer_idx on public.market_conversations (buyer_id, updated_at desc);
create index if not exists market_conversations_seller_idx on public.market_conversations (seller_id, updated_at desc);
create index if not exists market_messages_conversation_idx on public.market_messages (conversation_id, id);

alter table public.market_conversations enable row level security;
alter table public.market_messages enable row level security;
revoke all on public.market_conversations, public.market_messages from public, anon, authenticated;
grant select, insert, update on public.market_conversations to service_role;
grant select, insert, update on public.market_messages to service_role;
grant usage, select on all sequences in schema public to service_role;
