create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete restrict,
  title text not null,
  content text not null,
  status text not null default 'DRAFT',
  view_count bigint not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_title_length check (char_length(title) between 1 and 100),
  constraint posts_content_length check (char_length(content) between 1 and 20000),
  constraint posts_status check (status in ('DRAFT', 'PUBLISHED')),
  constraint posts_published_time check (
    (status = 'DRAFT' and published_at is null)
    or (status = 'PUBLISHED' and published_at is not null)
  ),
  constraint posts_view_count_nonnegative check (view_count >= 0)
);

create index if not exists posts_blog_id_idx on public.posts (blog_id);
create index if not exists posts_public_feed_idx on public.posts (status, published_at desc, id desc);
alter table public.posts enable row level security;

create or replace view public.post_details
with (security_invoker = true)
as
select
  p.id,
  p.blog_id,
  p.title,
  p.content,
  p.status,
  p.view_count,
  p.published_at,
  p.created_at,
  p.updated_at,
  b.name as blog_name,
  b.slug as blog_slug,
  b.owner_id,
  u.nickname as author_nickname
from public.posts p
join public.blogs b on b.id = p.blog_id
join public.users u on u.id = b.owner_id;

revoke all on public.post_details from public, anon, authenticated;
grant select on public.post_details to service_role;

create or replace function public.read_post(p_post_id bigint, p_request_user_id bigint default null)
returns setof public.post_details
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.post_details%rowtype;
begin
  select * into target from public.post_details where id = p_post_id;
  if not found then return; end if;
  if target.status = 'DRAFT' and target.owner_id is distinct from p_request_user_id then return; end if;

  if target.status = 'PUBLISHED' then
    update public.posts set view_count = view_count + 1 where id = p_post_id;
    target.view_count := target.view_count + 1;
  end if;
  return next target;
end;
$$;

revoke all on function public.read_post(bigint, bigint) from public, anon, authenticated;
grant execute on function public.read_post(bigint, bigint) to service_role;
